import artifact from "@/data/horizon-bootstrap.json";
import type { FrequencyArtifact } from "@/lib/horizon/probability";

/**
 * Deterministic simulation-derived bootstrap generated by
 * `npm run horizon:bootstrap -- --write`. It is never TxLINE historical data.
 */
export const SIMULATION_BOOTSTRAP = artifact as FrequencyArtifact;
